### ISSUE TITLE
Backend: Would a MashineTranslator be beneficial?

### ISSUE THREAD

**Issue by x-moe-x** [hhu-stups/bmoth#23]
Handling raw MashineNodes seems to involve a lot of ugly looking code just to get it to z3. Would it make sense to encapsulate this into a separate translator?

**Comment by dohan** [comment]
MachineNodes should be handled by the de.bmoth.modelchecker.Modelchecker class.
What do you mean by a MachineTranslator? A translator similar to the FormulaTranslator?

**Comment by wysiib** [comment]
I think this would indeed be beneficial. However, we have to keep in mind, that translation needs to be adapted to certain use-cases:
For instance, in order to find the successor state of x=1 using the x:=x+1 assignment, the predicate to be solved is x=1 & x'=x+1. Maybe it is enough to implement a static translation inserting x_1 and / or x_2?

**Comment by wysiib** [comment]
has been implemented
