### ISSUE TITLE
STRG+Z can kill the app

### ISSUE THREAD

**Issue by Lunnaris01** [hhu-stups/bmoth#28]
Using STRG+z (undo) if not enough changes have been made crashes the app with
Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
	at org.fxmisc.undo.impl.UndoManagerImpl.undo(UndoManagerImpl.java:94)
	at org.fxmisc.richtext.model.UndoActions.undo(UndoActions.java:19)

https://github.com/TomasMikula/UndoFX

**Comment by Lunnaris01** [comment]
Seems to be fixed by 0f3b338

**Comment by Jessypet** [comment]
STRG+Z doesn't undo anything but deletes all the content in the editor

**Comment by Lunnaris01** [comment]
The history is just very slow, and uses large chunks, seems to be linked to being inactive in the CodeArea.
Try deleting a single line and reverting the change with strg+z afterwards, it should be working
Strg+z deletes all code as last step, because we start with an empty codeArea and load text from a file into it. if you open multiple different files, STRG+Z will jump back to the old code too.

**Comment by Jessypet** [comment]
"because we start with an empty codeArea", we don't if the last used file is opened again on start. So we should get the content of this file back instead of nothing.

Yes, deleting a single line can be reverted, but also only after some time. The delay is too big... adding some lines, removing the last one right afterwards and then undoing that removes all lines instead of giving me the last one back. Is there any way to speed that up?
