### ISSUE TITLE
REPL needs a pretty-printer

### ISSUE THREAD

**Issue by wysiib** [hhu-stups/bmoth#69]
Currently, we just use the toString method of the Z3 expressions.
It would be preferable to output B again.

Current behaviour:
```
x={1}
{x=[1 -> true, else -> false]}
```

Desired behaviour:
```
x={1}
{x={1}}
```

**Comment by Jessypet** [comment]
Sets are pretty, but intervals lead to the output of an extra argument: 

```
x : 0..4
{$t_1={}, x=0}
```
Not a problem in this case, because we can just remove it. But do we want intervals in sets? Because for this example

```
x = {0..2} & y = {1..3}
{$t_1={2,1,0}, y={(_ as-array k!30)}, $t_3={3,2,1}, x={(_ as-array k!28)}}
```
I'm not sure if there's any way to combine the corresponding elements as there's no order in the result and it gets confusing fast.

**Comment by wysiib** [comment]
i think we can filter out temporary identifiers. An identifier starting with "$" is not permitted in B anyway.
However, this should work:
```
x = {0..2} & y = {1..3}
{  x={ {0,1,2} }, y={ {1,2,3} }  }
```
I do not know which data structures are returned by Z3 and how we have to read them.
I think we should refactor the pretty printer into a separate class, so that it can be used for model checking counter examples as well. This way we can write separate test cases for the printer.

Afterwards, let us use individual issues for everything not printed as expected.
