### ISSUE TITLE
&, or: wrong operator precedence

### ISSUE THREAD

**Issue by x-moe-x** [hhu-stups/bmoth#76]
Given two formulas

1. `TRUE or (FALSE & FALSE)`
2. `TRUE or FALSE & FALSE`

which should be obviously satisfiable, `FormulaToZ3Translator::translatePredicate(...)` builds the following:

1. `(or true (and false false))`
2. `(and (or true false) false)`

This evaluates to `SAT` for 1. and `UNSAT` for 2.

**Comment by wysiib** [comment]
Has to be fixed in the parser, the translation does not handle precedences

**Comment by dohan** [comment]
The assumption is wrong that the second formula is satisfiable. 'or' and '&' both have priority 40.
Hence, TRUE or FALSE & FALSE is equivalent to (TRUE or FALSE) & FALSE which is obviously unsatisfiable.

**Comment by x-moe-x** [comment]
[Wikipedia says](https://en.m.wikipedia.org/wiki/Logical_connective#Order_of_precedence) it might have the same priority in some compilers. For convenience I suggest giving `&` a higher priority even if it's not striclty necessary.

**Comment by dohan** [comment]
Operator priorities differ in different formal languages. The [B reference manual](http://www.atelierb.eu/wp-content/uploads/sites/3/ressources/manrefb1.8.6.uk.pdf) (page 187 and following) says that both operators have the same priority. In order to be compatible with other tools for the B language we can't change these priorities. I personally prefer the way TLA+ handles priorities by reporting a "Precedence conflict between operators" while evaluating the formula "TRUE or FALSE & FALSE".

**Comment by wysiib** [comment]
I think we could add a warning in this case as well?

**Comment by dohan** [comment]
Yes, we can add a warning as we have a concrete syntax tree as well.
